server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: d7-enduser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/d7shop
    username: d7shop_dev
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

logging:
  level:
    org.springframework.security: DEBUG
    com.tranv.d7shop: DEBUG
  file:
    name: logs/d7-enduser-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      file-name-pattern: logs/archived/d7-enduser-service-%d{yyyy-MM-dd}.%i.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics 