spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/d7shop}
    username: ${DB_USERNAME:d7shop_dev}
    password: ${DB_PASSWORD:dev_password}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000}
      
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: ${FLYWAY_BASELINE:true}
    
  security:
    jwt:
      secret: ${JWT_SECRET:d7shop_development_jwt_secret_key_2024}
      expiration: ${JWT_EXPIRATION:86400000}
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}
      roles: ${ADMIN_ROLES:ADMIN}

  thymeleaf:
    cache: ${THYMELEAF_CACHE:false}
    
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.tranv.d7shop: ${LOG_LEVEL_APP:DEBUG}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: ${SERVER_ERROR_MESSAGE:always}
    include-binding-errors: ${SERVER_ERROR_BINDING:always}
    
springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH:/api-docs}
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
    enabled: ${SPRINGDOC_ENABLED:true}