spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/d7shop
    username: d7shop_dev
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  application:
    name: d7-library

jwt:
  secret: d7shop_jwt_secret_key_at_least_256_bits_long_for_development_only_please_change_in_production
  expiration: 86400000  # 24 hours
  refresh-expiration: 604800000  # 7 days 